# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Golfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=25)),
                ('last', models.CharField(max_length=25)),
                ('suffix', models.CharField(max_length=8)),
                ('tees', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=12)),
                ('team_role', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='golfer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handicaps.Team'),
        ),
    ]
