# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-06 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handicaps', '0002_auto_20180606_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Bye', 'Bye Team'), ('Inactive', 'Inactive')], max_length=12),
        ),
    ]
